Repository Nadim147c/waybar-lyric, pull requests merged in 2025-10, with the labels that each got.

#41 fix: spam of selecting player when none available
  cmd/execute.go
Labels: bug

#42 ci: add gh actions for release
  .github/workflows/release.yml
  build.sh
Labels: CI/CD

#43 chore: update v0.12.0 -> v0.12.2
  internal/config/config.go
Labels: release
